package com.example.meetmates.exception;

public enum ErrorCode {
    
    AUTH_BAD_PASSWORD,
    AUTH_UNAUTHORIZED,
    
    TOKEN_INVALID,
    TOKEN_EXPIRED,
    TOKEN_NOT_FOUND,

    USER_NOT_FOUND,
    USER_BANNED,
    USER_DISABLED,
    USER_DELETED,
    USER_EMAIL_USED,
    USER_ALREADY_VERIFIED,
    EMAIL_SEND_FAILED,
    ADDRESS_NOT_FOUND,

    ACTIVITY_NOT_FOUND,
    CATEGORY_NOT_FOUND,

    EVENT_NOT_FOUND,
    EVENT_FULL,
    EVENT_ALREADY_PARTICIPANT,
    EVENT_PENDING_ALREADY,
    EVENT_REQUEST_REJECTED,
    EVENT_FORBIDDEN,
    EVENT_INVALID_STATUS,
    EVENT_ORGANIZER_CANNOT_BE_REMOVED,
    PARTICIPANT_NOT_FOUND,
}
