spring.config.activate.on-profile=prod

# ===============================
# DATABASE (MySQL - Production)
# ===============================
spring.datasource.url=jdbc:mysql://localhost:3306/myapp_prod?useSSL=true&serverTimezone=UTC
spring.datasource.username=myapp_user
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# ===============================
# FRONTEND
# ===============================
app.frontend.url=https://www.myapp.com

# ===============================
# JWT
# ===============================
# 256 bits minimum (très important en prod)
app.jwtSecret=CHANGE_ME_ULTRA_SECRET_256_BITS_MINIMUM
# 15 minutes
app.jwtExpirationMs=900000
# 7 jours
app.jwtRefreshExpirationMs=604800000

# # ===============================
# # MAIL (ex: Gmail SMTP)
# # ===============================
# spring.mail.host=smtp.gmail.com
# spring.mail.port=587
# spring.mail.username=myapp@gmail.com
# spring.mail.password=CHANGE_ME_MAIL_PASSWORD
# spring.mail.properties.mail.smtp.auth=true
# spring.mail.properties.mail.smtp.starttls.enable=true

# app.mail.from=no-reply@myapp.com
