# APP CONFIG (TEST)
app.jwtSecret=test-secret-key-very-long-for-tests-only
app.jwtExpirationMs=86400000
app.frontend.url=http://localhost:3000

# DATASOURCE (H2)
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;MODE=PostgreSQL;DATABASE_TO_UPPER=false
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=root

# JPA / HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true

spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# SQL INIT
spring.sql.init.mode=never

# LOGGING DEBUG
logging.level.com.example.meetmates=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.tool.schema=DEBUG

# MAILLING
spring.mail.host=localhost
spring.mail.port=1025
spring.mail.username=test
spring.mail.password=test
spring.mail.test-connection=false

spring.flyway.enabled=false
spring.jpa.hibernate.ddl-auto=create-drop

app.mail.from=no-reply@test.local
