name: CI/CD Docker

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Give execute permission to mvnw
        run: chmod +x mvnw
        working-directory: MeetMatesBACK

      - name: Build & Run Tests
        run: ./mvnw clean verify
        working-directory: MeetMatesBACK

      - name: Setup Tailscale (OAuth)
        uses: tailscale/github-action@v3
        with:
          oauth-client-id: ${{ secrets.TS_OAUTH_CLIENT_ID }}
          oauth-secret: ${{ secrets.TS_OAUTH_SECRET }}
          tags: tag:ci

      - name: Deploy to production via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ennio@100.118.36.88 << 'EOF'
            set -e

            cd ~/MeetMates

            echo "📥 Pulling repository"
            git pull

            echo "🛑 Stopping containers"
            docker compose down

            echo "🔨 Building images"
            docker compose build

            echo "🚀 Starting containers"
            docker compose up -d
          EOF
